"""SQLAlchemy models for Eagles Eye."""
from .base import Base, IdMixin, TimestampMixin, new_id, utcnow
from .entities import (
    AgentRun,
    Alert,
    ApprovalRequest,
    AuditLog,
    BehaviorEvent,
    Camera,
    Case,
    ChatMessage,
    CrowdSample,
    Evidence,
    GlobalSubject,
    Incident,
    IncidentTimelineEntry,
    ModelRecord,
    Report,
    Site,
    SystemMetric,
    Track,
    TrackedObject,
    User,
    WatchlistImage,
    WatchlistMatch,
    WatchlistSubject,
    Workflow,
    WorkflowRun,
    Zone,
)

__all__ = [
    "Base",
    "IdMixin",
    "TimestampMixin",
    "new_id",
    "utcnow",
    "AgentRun",
    "Alert",
    "ApprovalRequest",
    "AuditLog",
    "BehaviorEvent",
    "Camera",
    "Case",
    "ChatMessage",
    "CrowdSample",
    "Evidence",
    "GlobalSubject",
    "Incident",
    "IncidentTimelineEntry",
    "ModelRecord",
    "Report",
    "Site",
    "SystemMetric",
    "Track",
    "TrackedObject",
    "User",
    "WatchlistImage",
    "WatchlistMatch",
    "WatchlistSubject",
    "Workflow",
    "WorkflowRun",
    "Zone",
]

# Portal tables (organisations, accounts, activity trail).
from ..portal.models import Organisation, PortalAccount, PortalActivity  # noqa: E402,F401
