"""LLM integration, verified against a stub provider.

Runs a real OpenAI-compatible HTTP server in-process and points Sentinel at it,
so the wiring is proven end to end without needing anybody's API key. When you
add real credentials, the only thing that changes is the base URL.

The fallback behaviour is tested just as hard as the success path: an
unreachable or broken provider must degrade the *wording* of a narration, never
the capability. A dead LLM is not allowed to mean "no incident summary".
"""
from __future__ import annotations

import json
import threading
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any, Dict, List, Optional

import pytest

from app.agents.base import Finding
from app.agents.commander import IncidentCommander
from app.agents.threat import ThreatAssessor
from app.config import load_policy
from app.rag import llm as llm_module
from app.rag.llm import LLMClient, LLMUnavailable, extract_json

T0 = datetime(2026, 1, 15, 18, 42, 0, tzinfo=timezone.utc)


# ------------------------------------------------------------- stub server
class _Handler(BaseHTTPRequestHandler):
    """Minimal OpenAI-compatible /v1/chat/completions."""

    mode = "ok"                      # ok | error | garbage
    last_request: Optional[Dict[str, Any]] = None

    def log_message(self, *args):    # keep pytest output clean
        pass

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = json.loads(self.rfile.read(length) or b"{}")
        type(self).last_request = body

        if type(self).mode == "error":
            self.send_response(500)
            self.end_headers()
            self.wfile.write(b'{"error":"upstream exploded"}')
            return

        if type(self).mode == "garbage":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b"this is not json at all")
            return

        prompt = json.dumps(body.get("messages", []))
        reply = (
            "STUBBED NARRATION: a suitcase has been stationary near Gate 4 for 78 "
            "seconds with no associated subject nearby. Crowd density is moderate. "
            "Recommend operator review."
        )
        if "json" in prompt.lower() and "report" in prompt.lower():
            reply = "# Stub report\n\n- generated by the stub provider\n"

        payload = {
            "id": "chatcmpl-stub",
            "object": "chat.completion",
            "choices": [{"index": 0, "message": {"role": "assistant", "content": reply},
                         "finish_reason": "stop"}],
            "usage": {"prompt_tokens": 10, "completion_tokens": 20, "total_tokens": 30},
        }
        raw = json.dumps(payload).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)


@pytest.fixture(scope="module")
def stub_server():
    server = HTTPServer(("127.0.0.1", 0), _Handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    host, port = server.server_address
    yield f"http://{host}:{port}/v1"
    server.shutdown()
    server.server_close()


@pytest.fixture
def stub_llm(stub_server, monkeypatch):
    """Point the global LLM client at the stub."""
    _Handler.mode = "ok"
    client = LLMClient()
    client.provider = "openai_compatible"
    client.base_url = stub_server
    client.api_key = "stub-key"
    client.model = "stub-model"
    monkeypatch.setattr(llm_module, "_client", client)
    monkeypatch.setattr(llm_module, "get_llm", lambda: client)

    import app.agents.commander as commander_module
    import app.rag.forensic as forensic_module

    monkeypatch.setattr(commander_module, "get_llm", lambda: client)
    monkeypatch.setattr(forensic_module, "get_llm", lambda: client)
    return client


# --------------------------------------------------------------- the client
def test_disabled_provider_reports_itself_honestly():
    client = LLMClient()
    client.provider = "none"
    assert client.enabled is False
    assert client.info()["enabled"] is False
    with pytest.raises(LLMUnavailable):
        client.complete([{"role": "user", "content": "hello"}])


def test_health_check_round_trips(stub_llm):
    health = stub_llm.health()
    assert health["ok"] is True
    assert health["provider"] == "openai_compatible"
    assert health["model"] == "stub-model"


def test_completion_sends_a_well_formed_request(stub_llm):
    reply = stub_llm.complete(
        [{"role": "system", "content": "be terse"}, {"role": "user", "content": "status?"}],
        temperature=0.1, max_tokens=64,
    )
    assert "STUBBED NARRATION" in reply

    sent = _Handler.last_request
    assert sent["model"] == "stub-model"
    assert sent["temperature"] == 0.1
    assert sent["max_tokens"] == 64
    assert [m["role"] for m in sent["messages"]] == ["system", "user"]


def test_upstream_failure_raises_llm_unavailable(stub_llm):
    _Handler.mode = "error"
    try:
        with pytest.raises(LLMUnavailable):
            stub_llm.complete([{"role": "user", "content": "hi"}])
    finally:
        _Handler.mode = "ok"


def test_json_extraction_survives_prose_and_fences():
    assert extract_json('{"a": 1}') == {"a": 1}
    assert extract_json('```json\n{"a": 2}\n```') == {"a": 2}
    assert extract_json('Sure! Here you go:\n{"a": 3}\nHope that helps.') == {"a": 3}
    assert extract_json("[1, 2, 3]") == [1, 2, 3]
    with pytest.raises(ValueError):
        extract_json("no json here at all")


# ------------------------------------------------------------ the commander
def _assessment():
    findings = [Finding("unattended_object", 0.92, "high", started_at=T0, ended_at=T0,
                        explanation="A suitcase has been stationary for 78s.")]
    return findings, ThreatAssessor().assess(findings, load_policy(), now=T0)


def test_narration_uses_the_llm_when_one_is_configured(stub_llm):
    findings, assessment = _assessment()
    out = IncidentCommander().compose(
        findings=findings, assessment=assessment,
        camera={"id": "CAM_1", "name": "Gate 4", "location": "Terminal A"}, now=T0,
    )
    assert out["narration_source"] == "llm:openai_compatible"
    assert "STUBBED NARRATION" in out["summary"]


def test_narration_falls_back_to_template_when_the_llm_breaks(stub_llm):
    """A dead provider must cost wording, never capability."""
    _Handler.mode = "error"
    try:
        findings, assessment = _assessment()
        commander = IncidentCommander()
        out = commander.compose(
            findings=findings, assessment=assessment,
            camera={"id": "CAM_1", "name": "Gate 4", "location": "Terminal A"}, now=T0,
        )
        assert out["narration_source"] == "template"
        assert out["summary"], "the fallback produced no summary at all"
        assert "stationary" in out["summary"].lower()
        # Everything else must still be present.
        assert out["recommended_actions"]
        assert out["timeline"]
        assert out["risk_factors"]
        assert commander.llm_failures == 1
    finally:
        _Handler.mode = "ok"


def test_llm_narration_still_carries_the_guardrails(stub_llm):
    """The system prompt must state the limits the platform enforces."""
    import app.agents.commander as commander_module

    prompt = commander_module.SYSTEM_PROMPT.lower()
    for rule in ("never assert a person's identity",
                 "never infer the contents",
                 "recommend actions for a human to approve"):
        assert rule in prompt, f"the system prompt dropped: {rule}"


# -------------------------------------------------------------- forensic
def test_forensic_answer_uses_the_llm(stub_llm, monkeypatch):
    from app.rag.forensic import ForensicSearch
    from app.rag.vectorstore import MemoryStore, incident_to_document

    store = MemoryStore()
    store.upsert([incident_to_document({
        "id": "INC_LLM001", "title": "Potentially unattended object",
        "summary": "A suitcase near Gate 4 has been stationary for 78 seconds.",
        "explanation": "Risk driven by unattended_object.",
        "behaviors": ["unattended_object"], "camera_id": "CAM_1",
        "camera_name": "Gate 4", "zone_id": "Z1", "site_id": "S1",
        "event_type": "unattended_object", "severity": "high", "risk_score": 78.0,
        "started_at": T0.isoformat(), "location": {"zone_name": "Gate 4"},
        "track_ids": ["T_104"],
    })])
    import app.rag.forensic as forensic_module

    monkeypatch.setattr(forensic_module, "get_store", lambda: store)

    result = ForensicSearch().answer("unattended suitcase near gate 4", now=T0)
    assert result["answer_source"] == "llm:openai_compatible"
    assert "STUBBED NARRATION" in result["answer"]
    # Grounding must survive: citations come from retrieval, not from the model.
    assert [c["incident_id"] for c in result["citations"]] == ["INC_LLM001"]


def test_forensic_falls_back_and_still_cites(stub_llm, monkeypatch):
    from app.rag.forensic import ForensicSearch
    from app.rag.vectorstore import MemoryStore, incident_to_document

    store = MemoryStore()
    store.upsert([incident_to_document({
        "id": "INC_LLM002", "title": "Restricted-zone entry",
        "summary": "Subject entered the apron.", "explanation": "Risk driven by restricted_entry.",
        "behaviors": ["restricted_entry"], "camera_id": "CAM_2", "camera_name": "Apron",
        "zone_id": "Z2", "site_id": "S1", "event_type": "restricted_entry",
        "severity": "high", "risk_score": 60.0, "started_at": T0.isoformat(),
        "location": {}, "track_ids": [],
    })])
    import app.rag.forensic as forensic_module

    monkeypatch.setattr(forensic_module, "get_store", lambda: store)

    _Handler.mode = "error"
    try:
        result = ForensicSearch().answer("restricted zone entries", now=T0)
        assert result["answer_source"] == "template"
        assert result["answer"]
        assert [c["incident_id"] for c in result["citations"]] == ["INC_LLM002"]
    finally:
        _Handler.mode = "ok"


def test_provider_switching_needs_no_code_change(stub_server):
    """Every supported provider builds a client from configuration alone."""
    for provider in ("openai_compatible", "ollama", "anthropic", "mistral"):
        client = LLMClient()
        client.provider = provider
        client.base_url = stub_server
        client.api_key = "k"
        client.model = "m"
        assert client.enabled is True, f"{provider} would not enable from config"
        assert client.info()["provider"] == provider
