import { useEffect, useState } from 'react'
import { Card, Empty, ErrorNote, Field, Icon, Loading, Modal, PageHeader, toast } from '../components/ui'
import { ApiError, api, type Paged } from '../lib/api'
import { useAuth } from '../lib/auth'
import { dateTimeOf, relativeTime, titleCase } from '../lib/format'
import { useApi } from '../lib/hooks'

interface Report {
  id: string
  title: string
  report_type: string
  period_start: string | null
  period_end: string | null
  generated_by: string
  created_at: string
  stats: Record<string, any>
  body_markdown?: string
}

export default function ReportsPage() {
  const { can } = useAuth()
  const [open, setOpen] = useState(false)
  const [selected, setSelected] = useState<string | null>(null)
  const [form, setForm] = useState({ title: '', report_type: 'daily', hours: 24 })
  const [busy, setBusy] = useState(false)

  const { data, loading, error, reload } = useApi<Paged<Report>>('/api/admin/reports', { limit: 100 })
  const { data: detail } = useApi<Report>(selected ? `/api/admin/reports/${selected}` : null)

  useEffect(() => {
    document.title = 'Reports · Eagles Eye'
  }, [])

  async function generate() {
    setBusy(true)
    try {
      const report = await api.post<Report>('/api/admin/reports/generate', {
        title: form.title || null,
        report_type: form.report_type,
        hours: Number(form.hours),
      })
      toast('Report generated')
      setOpen(false)
      setSelected(report.id)
      reload()
    } catch (err) {
      toast(err instanceof ApiError ? err.message : String(err), 'error')
    } finally {
      setBusy(false)
    }
  }

  function download() {
    if (!detail?.body_markdown) return
    const blob = new Blob([detail.body_markdown], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `${detail.id}.md`
    anchor.click()
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <PageHeader
        title="Reports"
        subtitle="Generated from recorded incidents — figures come from the database, not an estimate"
        actions={
          can('report:write') ? (
            <button className="btn-primary" onClick={() => setOpen(true)}>
              <Icon name="post_add" className="text-[16px]" />
              Generate report
            </button>
          ) : null
        }
      />

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-space-lg items-start">
        <Card className="xl:col-span-1" title="Generated reports" bodyClassName="p-0">
          {error ? (
            <div className="p-space-md"><ErrorNote message={error} onRetry={reload} /></div>
          ) : loading && !data ? (
            <Loading />
          ) : !data || data.items.length === 0 ? (
            <Empty icon="description" title="No reports yet" />
          ) : (
            <ul className="divide-y divide-outline-variant/25 max-h-[70vh] overflow-y-auto">
              {data.items.map((report) => (
                <li key={report.id}>
                  <button
                    className={`w-full text-left p-space-md hover:bg-surface transition-colors ${
                      selected === report.id ? 'bg-surface-container-low' : ''
                    }`}
                    onClick={() => setSelected(report.id)}
                  >
                    <p className="font-headline-sm text-headline-sm truncate">{report.title}</p>
                    <p className="mono text-outline">
                      {titleCase(report.report_type)} · {relativeTime(report.created_at)} ·{' '}
                      {report.stats?.incidents_total ?? 0} incidents
                    </p>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </Card>

        <Card
          className="xl:col-span-2"
          title={detail?.title ?? 'Report'}
          actions={
            detail ? (
              <button className="btn-secondary btn-xs" onClick={download}>
                <Icon name="download" className="text-[14px]" />
                Markdown
              </button>
            ) : null
          }
        >
          {!detail ? (
            <Empty icon="article" title="Select a report" hint="Pick one on the left, or generate a new one." />
          ) : (
            <div className="flex flex-col gap-space-lg">
              <dl className="grid grid-cols-2 sm:grid-cols-4 gap-space-md">
                <Stat label="Period" value={`${dateTimeOf(detail.period_start)} → ${dateTimeOf(detail.period_end)}`} />
                <Stat label="Generated by" value={detail.generated_by} />
                <Stat label="Incidents" value={String(detail.stats?.incidents_total ?? 0)} />
                <Stat label="Highest risk" value={`${detail.stats?.highest_risk ?? 0}%`} />
              </dl>
              <article className="prose-sentinel">
                <Markdown text={detail.body_markdown ?? ''} />
              </article>
            </div>
          )}
        </Card>
      </div>

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        title="Generate a report"
        footer={
          <>
            <button className="btn-secondary" onClick={() => setOpen(false)}>Cancel</button>
            <button className="btn-primary" onClick={generate} disabled={busy}>
              {busy ? <Icon name="progress_activity" className="animate-spin text-[16px]" /> : null}
              Generate
            </button>
          </>
        }
      >
        <div className="flex flex-col gap-space-md">
          <Field label="Title" hint="Leave blank for an automatic title.">
            <input className="input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
          </Field>
          <Field label="Type">
            <select className="input" value={form.report_type} onChange={(e) => setForm({ ...form, report_type: e.target.value })}>
              {['daily', 'shift', 'weekly', 'incident', 'executive'].map((type) => (
                <option key={type} value={type}>{titleCase(type)}</option>
              ))}
            </select>
          </Field>
          <Field label="Period (hours)">
            <input type="number" className="input" value={form.hours} onChange={(e) => setForm({ ...form, hours: Number(e.target.value) })} />
          </Field>
        </div>
      </Modal>
    </>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0">
      <dt className="label">{label}</dt>
      <dd className="mono text-on-surface truncate" title={value}>{value}</dd>
    </div>
  )
}

/** Minimal markdown renderer — headings, lists, tables, bold and rules. */
function Markdown({ text }: { text: string }) {
  const lines = text.split('\n')
  const out: JSX.Element[] = []
  let table: string[][] | null = null
  let list: string[] | null = null

  const flush = () => {
    if (table) {
      const [head, ...rows] = table.filter((r) => !r.every((c) => /^-+$/.test(c.trim())))
      out.push(
        <div className="table-wrap my-space-md" key={`t-${out.length}`}>
          <table className="tbl">
            <thead>
              <tr>{head.map((cell, i) => <th key={i}>{cell}</th>)}</tr>
            </thead>
            <tbody>
              {rows.map((row, r) => (
                <tr key={r}>{row.map((cell, c) => <td key={c}>{cell}</td>)}</tr>
              ))}
            </tbody>
          </table>
        </div>,
      )
      table = null
    }
    if (list) {
      out.push(
        <ul className="list-disc pl-5 my-space-sm flex flex-col gap-0.5" key={`l-${out.length}`}>
          {list.map((item, i) => (
            <li key={i} className="font-body-sm text-body-sm" dangerouslySetInnerHTML={{ __html: inline(item) }} />
          ))}
        </ul>,
      )
      list = null
    }
  }

  for (const raw of lines) {
    const line = raw.trimEnd()
    if (line.startsWith('|')) {
      table = table ?? []
      table.push(line.split('|').slice(1, -1).map((c) => c.trim()))
      continue
    }
    if (line.startsWith('- ')) {
      list = list ?? []
      list.push(line.slice(2))
      continue
    }
    flush()
    if (!line.trim()) continue
    if (line.startsWith('### ')) out.push(<h3 key={out.length} className="font-headline-sm text-headline-sm mt-space-md">{line.slice(4)}</h3>)
    else if (line.startsWith('## ')) out.push(<h2 key={out.length} className="font-headline-md text-headline-md mt-space-lg">{line.slice(3)}</h2>)
    else if (line.startsWith('# ')) out.push(<h1 key={out.length} className="font-headline-lg text-headline-lg">{line.slice(2)}</h1>)
    else if (line.startsWith('---')) out.push(<hr key={out.length} className="my-space-md border-outline-variant/40" />)
    else out.push(<p key={out.length} className="font-body-sm text-body-sm my-1" dangerouslySetInnerHTML={{ __html: inline(line) }} />)
  }
  flush()
  return <>{out}</>
}

function inline(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/_(.+?)_/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code class="mono">$1</code>')
}
